### ISSUE TITLE
Questions on usuage

### ISSUE THREAD

**Issue by gelsas** [r4victor/syncabook#1]
Hello!

I have just found your repository and it seems that this is exactly what I am looking for.

Is there a GUI available for complete beginners like me. Reading the instructions make is sound quite complicated for me.

I have some ebooks in epub format and I have an audiobook of these ebooks, where each mp3 file equals one chapter of the book.

Would your tool be able to create an ebook with synchronized text and audio when I have the files like described above ?

If yes how good/accurate is the alignment?

(Does your tool work the same way as [aeneas ](https://github.com/readbeyond/aeneas) or is it using completly different method to do the syncing?)

**Comment by r4victor** [comment]
Hello! Unfortunately, the GUI for syncabook is not available. Synchronized EPUB ebook cannot be produced directly from another EPUB file, you need to prepare a list XHTML files containing fragments (units of synchronization), one file per chapter. This is done using `to_xhtml` command which converts plain text files to XHTMLs. So you may copy the contents of the EPUB ebook to the plain text files and follow the instructions.

I recommend you to follow the example in the readme. Just copy line by line and see the result. This is much easier than trying to understand the process just by reading my tangled prose.

I haven't measured the alignment accuracy quantitatively. It feels good. It should be at least as good as aeneas – the alignment algorithm is the same except the syncabook can handle some non-matching content and works faster.

**Comment by gelsas** [comment]
Hi thank you for your quick response.

I have googled a bit and what I have found out, is that the library mentioned below will convert an epub to I think xhtml chapter by chapter:

This is the library
https://github.com/aerkalov/ebooklib

The code to generate the xhtml chapter by chapter I have found here: [Article](https://medium.com/@zazazakaria18/turn-your-ebook-to-text-with-python-in-seconds-2a1e42804913)

```
import ebooklib
from ebooklib import epub
def epub2thtml(epub_path):
    book = epub.read_epub(epub_path)
    chapters = []
    for item in book.get_items():
        if item.get_type() == ebooklib.ITEM_DOCUMENT:
            chapters.append(item.get_content())
    return chapters
```

Since I am a complete beginner I would like to ask if you maybe (if it is not to much to ask) could take a quick look if the xhtml files which this library would generate would work with your tool directly (so the epub to txt and the txt to xhtml step could be skipped). 
If yes that would make it much easier for someone like me to process epubs with your creation/application almost automatically.

**Comment by r4victor** [comment]
You can extract xhtml contents from the EPUB file using this tool but you cannot use any xhtml as an input for syncabook. The reason is that the synchronization is done by mapping text fragments to audio intervals and these text fragments have to be explicitly marked. Here is an [example](https://github.com/r4victor/synclibrivox/blob/master/books/a_christmas_carol/sync_text/1.xhtml). You can see that each fragment is span tag with its own id.

So it's not possible to skip to_xhtml step. You can avoid extracting the text manually using, as an option, the method showed in the article.

**Comment by gelsas** [comment]
Will your script work  if I have a whole ebook as epub file and one single mp3 which covers the whole book ?

If yes I will give it a try because it seems to be easy to handle for a beginner like me when it is just 1 single file each.

One more question, all the formating which was present in the original epub will get lost right ?

Is there anyway that you could maybe modify your script to work directly with epubs ? (I would even pay for such a functionality to be added)

**Comment by r4victor** [comment]
I decided not to modify existing epubs. It requires much more work. So I'm not going to introduce this functionality.

You can synchronize a single mp3.
