### ISSUE TITLE
afaligner does not install

### ISSUE THREAD

**Issue by ravigupta-design** [r4victor/syncabook#10]
I have been facing issues installing afaligner using pip on windows and ubuntu both. 
Importantly, 'aeneas' a dependency does not install.

**Comment by scillidan** [comment]
See here first, https://github.com/readbeyond/aeneas. To install `aeneas`.
You get `python37-32/python.exe` then.
To install `afaligner` with this python, refer to https://github.com/r4victor/afaligner.
Then, install `syncabook`.
It worked on Windows10.
```cmd
D:\home λ syncabook download_files https://librivox.org/alices-adventures-in-wonderland-by-lewis-carroll-2/ alice_in_wonderland
❗ The synclibrivox repository doesn't contain this book.
Downloading text from gutenberg.org...
❗ Link to the gutenberg.org is not found. Text won't be downloaded.
Downloading audio files...
100% (28153636 of 28153636) |#############################| Elapsed Time: 0:02:08 Time:  0:02:08
✔ Audio files have been downloaded to alice_in_wonderland\audio
```
