### ISSUE TITLE
Suggestion: Add Thorium

### ISSUE THREAD

**Issue by jeromecarney** [r4victor/syncabook#2]
With the imminent demise of Readium, Thorium looks to be a very good replacement reader for epubs with audio:
 
[https://github.com/edrlab/thorium-reader](https://github.com/edrlab/thorium-reader)

**Comment by r4victor** [comment]
Thanks for the suggestion. Thorium looks good indeed. I'll certainly add it to the list, but I have a question. I would like to choose a fragment to play by clicking on it, but Thorium also changes what's being played when I scroll. Do you know if it's possible to turn this off? I use Mac app.
