### ISSUE TITLE
Killed While generating SMIL Files

### ISSUE THREAD

**Issue by dawmyakhinoo** [r4victor/syncabook#20]
How can I prevent from being killed while generating SMIL Files.

```
size= 9707045kB time=15:39:15.42 bitrate=1411.0kbits/s speed= 232x
video:0kB audio:9707045kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000001%
Killed
```
![image](https://user-images.githubusercontent.com/98632502/214755611-a2b37bf4-7822-4244-a787-a9672765c715.png)

**Comment by r4victor** [comment]
Please re-open if reproduced.
