### ISSUE TITLE
Does syncabook supports Polish language?

### ISSUE THREAD

**Issue by chrisovato** [r4victor/syncabook#30]
Hi, would like to know if your tool supports Polish language?

**Comment by r4victor** [comment]
Hi, syncabook supports languages other than English via `--language`. I haven't tested Polish, but you can give it a try by passing `--language pol` to `syncabook sync` or `syncabook create`.

**Comment by chrisovato** [comment]
Thanks! Works as expected with `syncabook sync --language pol`
