### ISSUE TITLE
Epub cover

### ISSUE THREAD

**Issue by smhmd** [r4victor/syncabook#7]
Is there a way to automatically include a cover in the created epub (using `syncabook create`)?

**Comment by r4victor** [comment]
Hi, @smhmd. I've just pushed a commit that adds this functionality:

> To add a cover to the produced ebook, put a JPEG image named cover.jpg in the images/ directory before running syncabook create.

**Comment by smhmd** [comment]
I have a question on what you might use as a reader for EPUBs with media overlays? I'm having syncing issues with [Thorium](https://github.com/edrlab/thorium-reader) where the smil files are correct, yet the reader is weirdly out of sync.

**Comment by r4victor** [comment]
Yeah, there are very few of them. I listed all the readers I know in the README: https://github.com/r4victor/syncabook#how-to-read-and-listen

**Comment by smhmd** [comment]
One other thing, Victor. Could you include the default values for `ALIGNMENT_RADIUS` and `ALIGNMENT_SKIP_PENALTY` in `syncabook create` help text (I believe the radius is `100` and the skip penalty is `0.99`) and what should one set `ALIGNMENT_RADIUS` to if the preferred optimality over computational resources?
