### ISSUE TITLE
OSError dtwbd.so when using Docker for Windows

### ISSUE THREAD

**Issue by VintGryph** [r4victor/syncabook#8]
I created a docker container in Windows 10 as shown in the steps when installing syncabook. At the last step of 'sync' or 'create', this error pops up for the align step. I did see this error being marked as fixed in the afaligner issues, but I still face this error when going through the direct steps for syncabook

C:\Users\avina>docker run -v C:\books\mybook:/books/mybook syncabook create /books/mybook
ffmpeg version 4.3.3-0+deb11u1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mp3, from '/books/mybook/audio/pt1.mp3':
  Metadata:
    album           : Wheel of Time 01
    artist          : Robert Jordan & Brandon Sanderson
    comment         : Dallis24♥
    encoder         : Lavf54.63.104
    genre           : Audiobook
    title           : The Eye of the World pt.1
    track           : 1
  Duration: 16:42:33.91, start: 0.025056, bitrate: 32 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, mono, fltp, 32 kb/s
    Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 274x440 [SAR 100:100 DAR 137:220], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to '/books/mybook/smil/tmp/pt1_audio.wav':
  Metadata:
    IPRD            : Wheel of Time 01
    IART            : Robert Jordan & Brandon Sanderson
    ICMT            : Dallis24♥
    IPRT            : 1
    IGNR            : Audiobook
    INAM            : The Eye of the World pt.1
    ISFT            : Lavf58.45.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, mono, s16, 705 kb/s
    Metadata:
      encoder         : Lavc58.91.100 pcm_s16le
[wav @ 0x557b1364f180] Filesize 5305573186 invalid for wav, output file will be broken
size= 5181224kB time=16:42:33.88 bitrate= 705.6kbits/s speed= 333x
video:0kB audio:5181224kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000004%
Traceback (most recent call last):
  File "/usr/local/bin/syncabook", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/syncabook/__main__.py", line 153, in main
❗ SMIL files are not found. Synchronizing...
Calling afaligner for syncing...
    create_ebook(
  File "/usr/local/lib/python3.9/site-packages/syncabook/create.py", line 33, in create_ebook
    sync(
  File "/usr/local/lib/python3.9/site-packages/syncabook/sync.py", line 15, in sync
    sync_map = align(
  File "/usr/local/lib/python3.9/site-packages/afaligner/__init__.py", line 90, in align
    sync_map = build_sync_map(
  File "/usr/local/lib/python3.9/site-packages/afaligner/__init__.py", line 207, in build_sync_map
    _, path = c_FastDTWBD(text_mfcc_sequence, audio_mfcc_sequence, skip_penalty, radius=radius)
  File "/usr/local/lib/python3.9/site-packages/afaligner/c_dtwbd_wrapper.py", line 18, in c_FastDTWBD
    c_module = ctypes.cdll[os.path.join(BASE_DIR, 'c_modules/dtwbd.so')]
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 449, in __getitem__
    return getattr(self, name)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 444, in __getattr__
    dll = self._dlltype(name)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/site-packages/afaligner/c_modules/dtwbd.so: cannot open shared object file: No such file or directory

**Comment by r4victor** [comment]
syncabook's Dockerfile used the previous afaligner's version. Updated it. The problem should be fixed now.

**Comment by VintGryph** [comment]
Thank you for the quick response. I will check if it works now

**Comment by VintGryph** [comment]
I am facing this error now after restarting the process:

C:\Users\avina>docker run -v C:\books\mybook:/books/mybook syncabook create /books/mybook/
ffmpeg version 4.3.3-0+deb11u1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mp3, from '/books/mybook/audio/pt1.mp3':
  Metadata:
    album           : Wheel of Time 01
    artist          : Robert Jordan & Brandon Sanderson
    comment         : Dallis24♥
    encoder         : Lavf54.63.104
    genre           : Audiobook
    title           : The Eye of the World pt.1
    track           : 1
  Duration: 16:42:33.91, start: 0.025056, bitrate: 32 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, mono, fltp, 32 kb/s
    Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 274x440 [SAR 100:100 DAR 137:220], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to '/books/mybook/smil/tmp/pt1_audio.wav':
  Metadata:
    IPRD            : Wheel of Time 01
    IART            : Robert Jordan & Brandon Sanderson
    ICMT            : Dallis24♥
    IPRT            : 1
    IGNR            : Audiobook
    INAM            : The Eye of the World pt.1
    ISFT            : Lavf58.45.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, mono, s16, 705 kb/s
    Metadata:
      encoder         : Lavc58.91.100 pcm_s16le
[wav @ 0x563aee78c180] Filesize 5305573186 invalid for wav, output file will be broken
size= 5181224kB time=16:42:33.88 bitrate= 705.6kbits/s speed= 436x
video:0kB audio:5181224kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000004%
ERROR: malloc() failed when allocating D_matrix

**Comment by r4victor** [comment]
This is because afaligner doesn't work on Windows (https://github.com/r4victor/afaligner#supported-platforms). Some say it works if you install Linux in a VM.

**Comment by VintGryph** [comment]
Got it. Will check that out. Thanks
